export const GAME_STATUS = Object.freeze({
  LOBBY: 'LOBBY', SETUP: 'SETUP', DAWN: 'DAWN', DAY: 'DAY', NIGHT: 'NIGHT', FINISHED: 'FINISHED',
});

export const SUB_PHASE = Object.freeze({
  WAITING_ACTION: 'WAITING_ACTION', PLAY_CARDS: 'PLAY_CARDS', TRYAL_SELECTION: 'TRYAL_SELECTION',
  CONSPIRACY_RESOLUTION: 'CONSPIRACY_RESOLUTION', WITCH_SELECTION: 'WITCH_SELECTION',
  CONSTABLE_SELECTION: 'CONSTABLE_SELECTION', CONFESSION: 'CONFESSION', NIGHT_RESOLUTION: 'NIGHT_RESOLUTION',
  LAST_WORDS: 'LAST_WORDS',
});

export const ACTION = Object.freeze({
  START_GAME: 'START_GAME', RESET_GAME: 'RESET_GAME', SELECT_BLACK_CAT: 'SELECT_BLACK_CAT', DRAW_CARDS: 'DRAW_CARDS',
  PLAY_CARD: 'PLAY_CARD', END_TURN: 'END_TURN', SELECT_TRYAL: 'SELECT_TRYAL',
  SELECT_CONSPIRACY_CARD: 'SELECT_CONSPIRACY_CARD', SELECT_WITCH_VICTIM: 'SELECT_WITCH_VICTIM',
  SELECT_CONSTABLE_PROTECTION: 'SELECT_CONSTABLE_PROTECTION', CONFESS: 'CONFESS',
  PASS_CONFESSION: 'PASS_CONFESSION', SUBMIT_LAST_WORDS: 'SUBMIT_LAST_WORDS',
  END_LAST_WORDS: 'END_LAST_WORDS', APPLY_TIMEOUT: 'APPLY_TIMEOUT',
});

export const EVENT = Object.freeze({
  CARD_DRAWN: 'CARD_DRAWN', CARD_PLAYED: 'CARD_PLAYED', ACCUSATION_ADDED: 'ACCUSATION_ADDED',
  TRYAL_REVEALED: 'TRYAL_REVEALED', TRYAL_TRANSFERRED: 'TRYAL_TRANSFERRED',
  PLAYER_BECAME_WITCH: 'PLAYER_BECAME_WITCH', PLAYER_PROTECTED: 'PLAYER_PROTECTED',
  PLAYER_CONFESSED: 'PLAYER_CONFESSED', PLAYER_DIED: 'PLAYER_DIED', NIGHT_STARTED: 'NIGHT_STARTED',
  NIGHT_ENDED: 'NIGHT_ENDED', TURN_STARTED: 'TURN_STARTED', TURN_ENDED: 'TURN_ENDED',
  GAME_FINISHED: 'GAME_FINISHED', ROLE_CHANGED: 'ROLE_CHANGED', MARRIAGE_CARD_ASSIGNED: 'MARRIAGE_CARD_ASSIGNED',
  MARRIAGE_CREATED: 'MARRIAGE_CREATED',
});

export const TRYAL = Object.freeze({ NOT_WITCH: 'NOT_WITCH', WITCH: 'WITCH', CONSTABLE: 'CONSTABLE' });
export const CARD_COLOR = Object.freeze({ GREEN: 'GREEN', BLUE: 'BLUE', RED: 'RED', BLACK: 'BLACK' });
export const MIN_PLAYERS = 4;
export const MAX_PLAYERS = 12;
export const ACCUSATION_THRESHOLD = 7;
export const DECISION_TIMEOUT_MS = 45_000;
